// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iktftsxuuiyeabxgdxzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrdGZ0c3h1dWl5ZWFieGdkeHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzQ5NzUsImV4cCI6MjA2NzMxMDk3NX0.oP9zkV-gErD9NT76NZJefRHbqeBVXLE1j_cqTb5pp08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});